### ISSUE TITLE
Forwarding the file name to MQTT

### ISSUE THREAD

**Issue by svrooij** [stjohnjohnson/mqtt-camera-ftpd#3]
I want to try to forward the file name from the camera to the mqtt server.
That way I could try to differentiate between sound and motion detection. Hoping that my camera makes a difference between them.

Any ideas?
Will try to implement this myself.

**Comment by svrooij** [comment]
I created a new version of your camera to mqtt bridge, with no config file but only command line parameters.
[Ipcam2mqtt](https://github.com/svrooij/ipcam2mqtt/)

That also supports passing through the filename, so closing the issue here.

**Comment by stjohnjohnson** [comment]
Oooh.  I like your new one.  I'm going to deprecate this for that one.  👍
